'use client';
import {DatePicker,TimePicker} from '@/components/payroll-pickers';
import {useState} from 'react';
import {Plus,SlidersHorizontal,CalendarHeart,History,Clock3,Pencil} from 'lucide-react';
import {Checkbox} from '@/components/ui/checkbox';
import {Field,Choose,Modal} from './payroll-ui';
import {type Ledger,type Rule,applicable,today,uid,money,shortDate,validDate} from '@/lib/payroll';

type Props={data:Ledger;commit:(next:Ledger)=>Promise<void>;busy:boolean;readOnly:boolean};
export default function PayrollSettings({data,commit,busy,readOnly}:Props){
 const [modal,setModal]=useState(''),[error,setError]=useState(''),[roleId,setRoleId]=useState('cook'),[roleName,setRoleName]=useState(''),[color,setColor]=useState('#12a5a0'),[from,setFrom]=useState(today()),[amount,setAmount]=useState(''),[holidayName,setHolidayName]=useState(''),[multiplier,setMultiplier]=useState('3');
 const current=applicable(data.rules,today())||data.rules[0];
 const [rule,setRule]=useState<Rule>(current);
 const roles=data.roles.map(x=>({value:x.id,label:x.name+(x.active?'':' (đã ẩn)')}));
 function open(type:string,id?:string){setError('');setModal(type);setFrom(today());setAmount('');if(id)setRoleId(id);if(type==='role'){setRoleName('');setColor('#12a5a0')}if(type==='editRole'){const r=data.roles.find(x=>x.id===id)!;setRoleName(r.name);setColor(r.color)}if(type==='rule'){setRule({...current,from:today().slice(0,7)+'-01'});setFrom(today().slice(0,7)+'-01')}if(type==='holiday'){setHolidayName('');setMultiplier('3')}}
 async function submit(e:React.FormEvent){e.preventDefault();setError('');try{
  const next=structuredClone(data);
  if(modal==='role'||modal==='editRole'){
   if(!roleName.trim())throw new Error('Hãy nhập tên vị trí.');
   if(data.roles.some(x=>x.name.toLowerCase()===roleName.trim().toLowerCase()&&x.id!==(modal==='editRole'?roleId:'')))throw new Error('Tên vị trí đã tồn tại.');
   if(modal==='role')next.roles.push({id:uid(),name:roleName.trim(),color,active:true});
   else next.roles=next.roles.map(x=>x.id===roleId?{...x,name:roleName.trim(),color}:x);
  }else if(modal==='rate'){
   if(!validDate(from)||!Number.isFinite(Number(amount))||Number(amount)<=0||Number(amount)>10000000)throw new Error('Ngày và mức lương phải hợp lệ; lương lớn hơn 0.');
   if(data.rates.some(x=>x.roleId===roleId&&x.from===from))throw new Error('Vị trí đã có mức lương bắt đầu ngày này. Hãy chọn ngày áp dụng mới.');
   next.rates.push({id:uid(),roleId,from,amount:Number(amount)});
  }else if(modal==='holiday'){
   if(!validDate(from)||!holidayName.trim()||!Number.isFinite(Number(multiplier))||Number(multiplier)<1||Number(multiplier)>10)throw new Error('Hãy nhập ngày, tên ngày lễ và hệ số từ 1 đến 10.');
   next.holidays=next.holidays.filter(x=>x.date!==from);next.holidays.push({id:uid(),date:from,name:holidayName.trim(),multiplier:Number(multiplier)});
  }else if(modal==='rule'){
   if(!validDate(from))throw new Error('Ngày áp dụng không hợp lệ.');
   if(data.rules.some(x=>x.from===from))throw new Error('Đã có phiên bản quy tắc bắt đầu ngày này. Hãy chọn ngày khác.');
   if(rule.cutoff!==current.cutoff&&from.slice(-2)!=='01')throw new Error('Đổi ngày chốt công cần áp dụng từ ngày 01 của tháng.');
   if(data.settlements.some(x=>from<=x.end))throw new Error('Quy tắc mới phải bắt đầu sau các kỳ đã chốt.');
   const values=[rule.closingAmount,rule.cutoff,rule.payday,rule.rounding];
   if(values.some(x=>!Number.isFinite(x))||rule.closingAmount<0||rule.closingAmount>10000000||rule.cutoff<0||rule.cutoff>31||rule.payday<1||rule.payday>31||!Number.isInteger(rule.cutoff)||!Number.isInteger(rule.payday))throw new Error('Kiểm tra lại phụ cấp và ngày của kỳ lương.');
   next.rules.push({...rule,id:uid(),from});
  }
  await commit(next);setModal('');
 }catch(err){setError(err instanceof Error?err.message:'Không lưu được cài đặt.')}}
 async function toggleRole(id:string){try{await commit({...data,roles:data.roles.map(x=>x.id===id?{...x,active:!x.active}:x)})}catch(err){setError(String(err))}}
 return <><div className="settings-grid">
  <section className="card card-pad"><div className="section-head"><h2>Vị trí & mức lương</h2>{!readOnly&&<button className="btn icon" aria-label="Thêm vị trí" onClick={()=>open('role')}><Plus size={17}/></button>}</div><p className="helper">Mỗi vị trí có lịch sử mức lương riêng. Ca cũ giữ nguyên đơn giá đã lưu.</p>
   {data.roles.map(r=>{const rate=applicable(data.rates.filter(x=>x.roleId===r.id),today());return <div className="list-item" key={r.id}><div><span className="role-label"><i className="role-square" style={{background:r.color}}/>{r.name}{!r.active&&<span className="chip">Đã ẩn</span>}</span><small>{rate?money(rate.amount)+'/giờ':'Chưa thiết lập mức lương'}</small></div>{!readOnly&&<div className="row-actions"><button className="btn ghost icon" title="Sửa tên và màu" aria-label={'Sửa '+r.name} onClick={()=>open('editRole',r.id)}><Pencil size={15}/></button><button className="btn" onClick={()=>open('rate',r.id)}>Đổi lương</button></div>}</div>})}
   <div className="divider"/><h3 className="small">Lịch sử mức lương</h3><div className="history">{[...data.rates].sort((a,b)=>b.from.localeCompare(a.from)).map(r=><div className="list-item" key={r.id}><div>{data.roles.find(x=>x.id===r.roleId)?.name}<small>Từ {r.from==='2000-01-01'?'mức khởi tạo':shortDate(r.from)+'/'+r.from.slice(0,4)}</small></div><strong>{money(r.amount)}/h</strong></div>)}</div>
  </section>
  <section className="card card-pad"><div className="section-head"><h2>Quy tắc tính lương</h2>{!readOnly&&<button className="btn icon" aria-label="Thay đổi quy tắc" onClick={()=>open('rule')}><SlidersHorizontal size={17}/></button>}</div><div className="settings-values"><div><span>Vị trí đóng ca</span>{data.roles.find(x=>x.id===current.closingRole)?.name||'Không có'}</div><div><span>Giờ kết thúc</span>{current.closingTime}</div><div><span>Phụ cấp / ngày</span>{money(current.closingAmount)}</div><div><span>Phụ cấp ngày lễ</span>{current.holidayBonus?'Có nhân hệ số':'Không nhân hệ số'}</div><div><span>Ngày chốt công</span>{current.cutoff===0?'Cuối tháng':'Ngày '+current.cutoff}</div><div><span>Nhận lương</span>Ngày {current.payday} tháng sau</div><div><span>Làm tròn mỗi ca</span>{money(current.rounding)}</div><div><span>Cách làm tròn</span>{{nearest:'Gần nhất',down:'Làm tròn xuống',up:'Làm tròn lên'}[current.roundMode]}</div></div><p className="settings-note">Tính chính xác theo phút. Phụ cấp đóng ca tối đa 1 lần/ngày. Mốc ngày làm dùng giờ Việt Nam (UTC+7).</p><div className="divider"/><h3 className="small">Phiên bản quy tắc</h3><div className="history">{[...data.rules].sort((a,b)=>b.from.localeCompare(a.from)).map(r=><div className="list-item" key={r.id}><div><History size={14} className="inline mr-2"/> {r.from==='2000-01-01'?'Quy tắc khởi tạo':'Từ '+shortDate(r.from)+'/'+r.from.slice(0,4)}<small>Đóng ca {r.closingTime} · {money(r.closingAmount)} · {r.holidayBonus?'nhân hệ số lễ':'phụ cấp cố định'}</small></div></div>)}</div></section>
  <section className="card card-pad"><div className="section-head"><h2>Ngày lễ & hệ số</h2>{!readOnly&&<button className="btn icon" aria-label="Thêm ngày lễ" onClick={()=>open('holiday')}><Plus size={17}/></button>}</div><p className="helper">Nhập theo chính sách nơi làm việc. Ngày chưa cấu hình được tính hệ số ×1.</p>{data.holidays.length===0?<div className="empty-state"><CalendarHeart size={28} className="mx-auto mb-3 text-blue-400"/><p>Chưa thiết lập ngày lễ.</p>{!readOnly&&<button className="btn" onClick={()=>open('holiday')}>Thêm ngày lễ</button>}</div>:[...data.holidays].sort((a,b)=>a.date.localeCompare(b.date)).map(h=><div className="list-item" key={h.id}><div>{h.name}<small>{shortDate(h.date)}/{h.date.slice(0,4)}</small></div><div className="row-actions"><span className="chip">×{h.multiplier}</span>{!readOnly&&<button className="btn ghost icon" aria-label={'Sửa '+h.name} onClick={()=>{open('holiday');setFrom(h.date);setHolidayName(h.name);setMultiplier(String(h.multiplier))}}><Pencil size={15}/></button>}</div></div>)}</section>
  <section className="hint-card"><h3><Clock3 size={17}/> Áp dụng thay đổi</h3><p className="helper">Ca đã lưu giữ nguyên đơn giá. Muốn áp dụng cài đặt mới cho ca cũ, mở khóa kỳ rồi chọn “Tính lại kỳ” tại Đối chiếu.</p></section>
 </div><Modal open={!!modal} onClose={()=>setModal('')} title={{role:'Thêm vị trí',editRole:'Chỉnh vị trí',rate:'Mức lương mới',rule:'Phiên bản quy tắc mới',holiday:'Thiết lập ngày lễ'}[modal]||''} description="Thay đổi chỉ áp dụng trong sổ lương này."><form onSubmit={submit} className="form-stack">
 {(modal==='role'||modal==='editRole')&&<><Field label="Tên vị trí"><input value={roleName} onChange={e=>setRoleName(e.target.value)} required maxLength={40} placeholder="Ví dụ: Barista"/></Field><Field label="Màu nhận diện"><input type="color" value={color} onChange={e=>setColor(e.target.value)}/></Field>{modal==='editRole'&&<button type="button" disabled={busy} className="btn" onClick={async()=>{await toggleRole(roleId);setModal('')}}>{data.roles.find(x=>x.id===roleId)?.active?'Ẩn khỏi danh sách nhập ca':'Hiện lại vị trí'}</button>}</>}
 {modal==='rate'&&<><Field label="Vị trí"><Choose value={roleId} onChange={setRoleId} items={roles} label="Vị trí"/></Field><Field label="Lương mỗi giờ (đ)"><input type="number" min="1" max="10000000" step="1" required value={amount} onChange={e=>setAmount(e.target.value)} placeholder="Ví dụ: 27000"/></Field><Field label="Ngày bắt đầu áp dụng"><DatePicker label="Ngày bắt đầu áp dụng" value={from} onChange={setFrom}/></Field><p className="helper">Khi nhập bù, mức lương được chọn theo ngày làm. Ca đã lưu vẫn giữ mức trước đó.</p></>}
 {modal==='holiday'&&<><Field label="Ngày lễ"><DatePicker label="Ngày lễ" value={from} onChange={setFrom}/></Field><Field label="Tên ngày lễ"><input required maxLength={80} value={holidayName} onChange={e=>setHolidayName(e.target.value)} placeholder="Ví dụ: Quốc khánh"/></Field><Field label="Hệ số lương"><input type="number" min="1" max="10" step="0.01" required value={multiplier} onChange={e=>setMultiplier(e.target.value)}/></Field><p className="helper">Lưu cùng ngày sẽ cập nhật cấu hình của ngày đó. Ca đã nhập chỉ đổi khi bạn chủ động tính lại kỳ. Để bỏ hệ số, đặt về 1.</p></>}
 {modal==='rule'&&<><div className="form-grid"><Field label="Ngày bắt đầu" className="full"><DatePicker label="Ngày bắt đầu" value={from} onChange={setFrom}/></Field><Field label="Vị trí được phụ cấp"><Choose value={rule.closingRole} onChange={v=>setRule({...rule,closingRole:v})} items={roles} label="Vị trí đóng ca"/></Field><Field label="Kết thúc đúng lúc"><TimePicker label="Kết thúc đúng lúc" value={rule.closingTime} onChange={value=>setRule({...rule,closingTime:value})}/></Field><Field label="Phụ cấp tối đa/ngày (đ)" className="full"><input type="number" min="0" max="10000000" step="1" required value={rule.closingAmount} onChange={e=>setRule({...rule,closingAmount:Number(e.target.value)})}/></Field><Field label="Ngày chốt (0 = cuối tháng)"><input type="number" min="0" max="31" required value={rule.cutoff} onChange={e=>setRule({...rule,cutoff:Number(e.target.value)})}/></Field><Field label="Ngày nhận tháng sau"><input type="number" min="1" max="31" required value={rule.payday} onChange={e=>setRule({...rule,payday:Number(e.target.value)})}/></Field><Field label="Đơn vị làm tròn"><Choose value={String(rule.rounding)} onChange={v=>setRule({...rule,rounding:Number(v)})} items={[1,100,500,1000].map(n=>({value:String(n),label:money(n)}))} label="Đơn vị làm tròn"/></Field><Field label="Cách làm tròn"><Choose value={rule.roundMode} onChange={v=>setRule({...rule,roundMode:v as Rule['roundMode']})} items={[{value:'nearest',label:'Gần nhất'},{value:'down',label:'Làm tròn xuống'},{value:'up',label:'Làm tròn lên'}]} label="Cách làm tròn"/></Field></div><label className="checkrow"><Checkbox checked={rule.holidayBonus} onCheckedChange={v=>setRule({...rule,holidayBonus:v===true})}/>Nhân hệ số ngày lễ cho phụ cấp đóng ca</label><p className="helper">Ngày chốt/nhận vượt số ngày trong tháng sẽ dùng ngày cuối tháng. Thiết lập kỳ lương được chọn tại ngày 01 mỗi tháng.</p></>}
 {error&&<p role="alert" className="error-message">{error}</p>}<div className="form-footer"><button type="button" className="btn" onClick={()=>setModal('')}>Hủy</button><button disabled={busy||readOnly} className="btn primary" type="submit">{busy?'Đang lưu…':'Lưu cài đặt'}</button></div></form></Modal></>;
}
