'use client';
import {useEffect,useState,useCallback} from 'react';
import type {SupabaseClient,User} from '@supabase/supabase-js';
import {Search,ShieldCheck,LogOut,UserRound,Eye,UserRoundPlus} from 'lucide-react';
import {toast} from 'sonner';
import {Field,Blank} from './payroll-ui';
import type {Profile} from '@/lib/cloud';
import {errorMessage} from '@/lib/errors';
export default function AccountPanel({client,user,profile,onProfile,onView,busy}:{client:SupabaseClient|null;user:User|null;profile:Profile|null;onProfile:(p:Profile)=>void;onView:(p:Profile)=>Promise<void>;busy:boolean}){
 const [mode,setMode]=useState('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(profile?.display_name||''),[username,setUsername]=useState(profile?.username||''),[working,setWorking]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState(''),[results,setResults]=useState<Profile[]>([]),[searched,setSearched]=useState(false),[shares,setShares]=useState<Profile[]>([]),[incoming,setIncoming]=useState<Profile[]>([]);
 const refreshShares=useCallback(async()=>{if(!client||!user)return;const {data,error}=await client.from('ledger_shares').select('owner_id,viewer_id');if(error){setError(errorMessage(error));return}const ids=[...new Set((data||[]).flatMap(s=>[s.owner_id,s.viewer_id]).filter(id=>id!==user.id))];if(!ids.length){setShares([]);setIncoming([]);return}const p=await client.from('profiles').select('*').in('id',ids);if(p.error){setError(errorMessage(p.error));return}setShares((p.data||[]).filter(x=>data.some(s=>s.owner_id===user.id&&s.viewer_id===x.id)));setIncoming((p.data||[]).filter(x=>data.some(s=>s.viewer_id===user.id&&s.owner_id===x.id)))},[client,user])
 useEffect(()=>{const timer=setTimeout(()=>void refreshShares(),0);return()=>clearTimeout(timer)},[refreshShares]);
 async function auth(e:React.FormEvent){e.preventDefault();if(!client)return;setWorking(true);setError('');try{
  if(mode==='signup'){if(!name.trim())throw new Error('Hãy nhập tên hiển thị.');const {data,error}=await client.auth.signUp({email,password,options:{data:{display_name:name.trim()},emailRedirectTo:window.location.origin}});if(error)throw error;if(!data.session)toast.success('Hãy kiểm tra email để xác nhận đăng ký, sau đó đăng nhập.');else toast.success('Đã tạo tài khoản.');}
  else if(mode==='reset'){const {error}=await client.auth.resetPasswordForEmail(email,{redirectTo:window.location.origin+'/?recovery=1'});if(error)throw error;toast.success('Nếu email hợp lệ, bạn sẽ nhận được liên kết đặt lại mật khẩu.');}
  else {const {error}=await client.auth.signInWithPassword({email,password});if(error)throw error;toast.success('Đăng nhập thành công.');}
  setPassword('');
 }catch(e){setError(errorMessage(e))}finally{setWorking(false)}}
 async function saveProfile(e:React.FormEvent){e.preventDefault();if(!client||!user)return;setWorking(true);setError('');try{if(!/^[a-z0-9_]{3,30}$/.test(username))throw new Error('Username gồm 3–30 ký tự a–z, số hoặc dấu gạch dưới.');if(!name.trim())throw new Error('Hãy nhập tên hiển thị.');const next={id:user.id,username,display_name:name.trim()};const {error}=await client.from('profiles').upsert(next);if(error)throw error;onProfile(next);toast.success('Đã lưu hồ sơ.')}catch(e){setError(errorMessage(e))}finally{setWorking(false)}}
 async function search(e:React.FormEvent){e.preventDefault();if(!client)return;setWorking(true);setError('');try{const {data,error}=await client.rpc('search_profiles',{term:query.trim()});if(error)throw error;setResults((data||[]).filter((x:Profile)=>x.id!==user?.id));setSearched(true)}catch(e){setError(errorMessage(e))}finally{setWorking(false)}}
 async function share(p:Profile,revoke=false){if(!client||!user)return;setWorking(true);setError('');try{const r=revoke?await client.from('ledger_shares').delete().eq('owner_id',user.id).eq('viewer_id',p.id):await client.from('ledger_shares').insert({owner_id:user.id,viewer_id:p.id});if(r.error)throw r.error;await refreshShares();toast.success(revoke?'Đã thu hồi quyền xem.':'Đã cấp quyền xem cho @'+p.username);}catch(e){setError(errorMessage(e))}finally{setWorking(false)}}
 return <><div className="settings-grid"><section className="card card-pad"><div className="section-head"><h2>{user?'Hồ sơ của bạn':mode==='signup'?'Tạo tài khoản':mode==='reset'?'Đặt lại mật khẩu':'Đăng nhập'}</h2><UserRound size={20} className="muted"/></div>{!user?<><p className="helper mb-5">Đăng nhập để đồng bộ sổ lương và quản lý chia sẻ.</p>{!client&&<div className="banner">Chưa kết nối dịch vụ tài khoản. Dữ liệu hiện chỉ được lưu trên thiết bị.</div>}<form className="form-stack" onSubmit={auth}>{mode==='signup'&&<Field label="Tên hiển thị"><input required maxLength={80} value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></Field>}<Field label="Email"><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></Field>{mode!=='reset'&&<Field label="Mật khẩu"><input type="password" required minLength={8} value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==='signup'?'new-password':'current-password'}/></Field>}<button className="btn primary" disabled={!client||working||busy}>{working?'Đang xử lý…':mode==='signup'?'Tạo tài khoản':mode==='reset'?'Gửi liên kết đặt lại':'Đăng nhập'}</button><div className="row-actions"><button className="btn ghost" type="button" onClick={()=>{setMode(mode==='signup'?'login':'signup');setError('')}}>{mode==='signup'?'Đã có tài khoản':'Đăng ký tài khoản'}</button><button className="btn ghost" type="button" onClick={()=>{setMode(mode==='reset'?'login':'reset');setError('')}}>{mode==='reset'?'Quay lại':'Quên mật khẩu?'}</button></div></form></>:<form className="form-stack" onSubmit={saveProfile}><p className="helper">{user.email}</p><Field label="Tên hiển thị"><input value={name} required maxLength={80} onChange={e=>setName(e.target.value)}/></Field><Field label="Username"><input value={username} required minLength={3} maxLength={30} pattern="[a-z0-9_]{3,30}" onChange={e=>setUsername(e.target.value.toLowerCase())}/></Field><p className="helper">Người khác tìm bạn bằng tên hoặc username. Email không xuất hiện trong kết quả tìm kiếm.</p><button disabled={working||busy} className="btn primary">Lưu hồ sơ</button><button disabled={working||busy} type="button" className="btn" onClick={async()=>{setWorking(true);const r=await client!.auth.signOut();if(r.error)setError(errorMessage(r.error));else toast.success('Đã đăng xuất.');setWorking(false)}}><LogOut size={16}/>Đăng xuất</button></form>}</section>
 <section className="card card-pad"><div className="section-head"><h2>Tìm người dùng</h2><Search size={19} className="muted"/></div>{user?<><form className="search-form" onSubmit={search}><input aria-label="Tên hoặc username" placeholder="Tên hoặc username…" value={query} onChange={e=>setQuery(e.target.value)} minLength={2} maxLength={80} required/><button className="btn primary icon" disabled={working} aria-label="Tìm kiếm"><Search size={18}/></button></form><p className="helper">Chỉ xem được sổ lương khi người đó cấp quyền. “Chia sẻ” bên dưới cấp cho họ quyền xem sổ của bạn.</p>{results.map(p=><div className="list-item" key={p.id}><div className="user-profile"><div className="avatar">{p.display_name.charAt(0).toUpperCase()}</div><div>{p.display_name}<small>@{p.username}</small></div></div><div className="row-actions"><button className="btn icon" aria-label={'Xem sổ của '+p.display_name} onClick={()=>onView(p).catch(e=>setError(errorMessage(e)))}><Eye size={16}/></button><button disabled={working||shares.some(s=>s.id===p.id)} className="btn" onClick={()=>share(p)}>{shares.some(s=>s.id===p.id)?'Đã chia sẻ':'Chia sẻ'}</button></div></div>)}{searched&&!results.length&&<p className="helper mt-5">Không tìm thấy người dùng phù hợp.</p>}</>:<Blank title="Cần đăng nhập" text="Đăng nhập để tìm người dùng và quản lý quyền xem sổ lương."/>}</section>
 {user&&<><section className="card card-pad"><div className="section-head"><h2>Ai được xem sổ của bạn</h2><ShieldCheck size={19} className="muted"/></div><p className="helper">Quyền xem bao gồm lịch làm, mức lương, cài đặt và lương thực nhận. Người được chia sẻ không thể sửa dữ liệu.</p>{!shares.length&&<p className="helper mt-5">Chưa chia sẻ với ai.</p>}{shares.map(p=><div className="list-item" key={p.id}><div>{p.display_name}<small>@{p.username}</small></div><button className="btn" disabled={working} onClick={()=>share(p,true)}>Thu hồi</button></div>)}</section><section className="card card-pad"><div className="section-head"><h2>Được chia sẻ với bạn</h2><UserRoundPlus size={19} className="muted"/></div>{!incoming.length&&<p className="helper">Chưa có sổ lương được chia sẻ.</p>}{incoming.map(p=><div className="list-item" key={p.id}><div>{p.display_name}<small>@{p.username}</small></div><button className="btn" onClick={()=>onView(p).catch(e=>setError(errorMessage(e)))}>Xem sổ</button></div>)}</section></>}
 </div>{error&&<p role="alert" className="error-message mt-5">{error}</p>}</>;
}
